{
 "title": "anamoly detection dashboard",
 "time": { "from": "2025-09-26T11:39:11.840Z", "to": "2025-11-25T11:39:11.840Z" },
 "panels": [
  { "title": "Production Health Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Anomaly_Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "TestDB",
     "rawSql": "SELECT COUNT(*) AS AnomaliesToday\r\nFROM MES_Production_Anomalies\r\nWHERE CAST(DetectionTime AS DATE) = CAST(GETDATE() AS DATE)"
    }
   ]
  },
  {
   "title": " Cycle Time Trend",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sec/cycle" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "TestDB",
     "rawSql": "SELECT StartTime AS time,\r\n       DATEDIFF(MINUTE, StartTime, EndTime) AS value\r\nFROM MES_ProductionData\r\nWHERE $__timeFilter(StartTime)\r\nORDER BY StartTime ASC"
    }
   ]
  },
  {
   "title": "anomaly timseries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "TestDB",
     "rawSql": "SELECT\r\n  CAST(DetectionTime AS DATE) AS time,\r\n  COUNT(*) AS value\r\nFROM MES_Production_Anomalies\r\nWHERE $__timeFilter(DetectionTime)\r\nGROUP BY CAST(DetectionTime AS DATE)\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Top 10 Production Anomaly",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "TestDB",
     "rawSql": "SELECT TOP 10 RecordID, AnomalyScore, DetectionTime\r\nFROM MES_Production_Anomalies\r\nORDER BY AnomalyScore ASC"
    }
   ]
  },
  {
   "title": "Defect Ratio",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "TestDB",
     "rawSql": "SELECT AVG(CAST(Defects AS FLOAT) / NULLIF(QuantityProduced, 0)) AS AvgDefectsRatio\r\nFROM MES_ProductionData\r\nWHERE $__timeFilter(StartTime)"
    }
   ]
  },
  {
   "title": "Avg production rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "units/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "TestDB",
     "rawSql": "SELECT AVG(CAST(QuantityProduced AS FLOAT) /\r\n           NULLIF(DATEDIFF(MINUTE, StartTime, EndTime), 0)) AS AvgProductionRate\r\nFROM MES_ProductionData\r\nWHERE $__timeFilter(StartTime)"
    }
   ]
  }
 ]
}