{
 "title": "DigitalTwin Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "machineID",
    "label": "machineID",
    "query": "MCH001,MCH002,MCH003,MCH004,MCH005,MCH006,MCH007,MCH008,MCH009,MCH010"
   }
  ]
 },
 "panels": [
  {
   "title": "Digital Twin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Asset Data",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "componentName": "MachineDataSource",
       "entityId": "584a39cc-3748-495d-a7c6-a22ecab89672",
       "properties": [
        "MachineID",
        "MachineTemp",
        "EnergyConsumed",
        "Status",
        "Pressure",
        "EnvTemp",
        "Humidity",
        "PowerPeak",
        "CO2Level"
       ]
      },
      {
       "componentName": "MachineDataSource",
       "entityId": "7a5a34de-410d-4b2e-b36f-94c0e2e2089d",
       "properties": [
        "CO2Level",
        "EnvTemp",
        "PowerPeak",
        "Humidity",
        "MachineID",
        "MachineTemp",
        "Pressure",
        "EnergyConsumed",
        "Status"
       ]
      },
      {
       "componentName": "MachineDataSource",
       "entityId": "48d9f3c4-3405-4e8e-b904-00f2ea9510f0",
       "properties": [
        "EnvTemp",
        "MachineID",
        "MachineTemp",
        "EnergyConsumed",
        "Pressure",
        "CO2Level",
        "Humidity",
        "PowerPeak",
        "Status"
       ]
      },
      {
       "componentName": "MachineDataSource",
       "entityId": "949b236a-789c-4314-96aa-6195598509bd",
       "properties": [
        "Humidity",
        "EnvTemp",
        "PowerPeak",
        "EnergyConsumed",
        "MachineTemp",
        "Pressure",
        "Status",
        "CO2Level",
        "MachineID"
       ]
      },
      {
       "componentName": "MachineDataSource",
       "entityId": "5f15d4fd-27cf-4b51-ad15-38703bea0575",
       "properties": [
        "PowerPeak",
        "MachineTemp",
        "CO2Level",
        "Status",
        "EnvTemp",
        "EnergyConsumed",
        "MachineID",
        "Pressure",
        "Humidity"
       ]
      },
      {
       "componentName": "MachineDataSource",
       "entityId": "373e9965-d7ad-41b3-aae0-681b646a1501",
       "properties": [
        "EnvTemp",
        "PowerPeak",
        "Status",
        "EnergyConsumed",
        "MachineTemp",
        "Pressure",
        "CO2Level",
        "Humidity",
        "MachineID"
       ]
      },
      {
       "componentName": "MachineDataSource",
       "entityId": "fa2d379a-b4d3-4cf3-adbf-84daa95d7875",
       "properties": [
        "MachineID",
        "Pressure",
        "CO2Level",
        "PowerPeak",
        "EnergyConsumed",
        "MachineTemp",
        "Status",
        "Humidity",
        "EnvTemp"
       ]
      },
      {
       "componentName": "MachineDataSource",
       "entityId": "2bb32d83-4304-49d0-bb65-7cdc150a69ed",
       "properties": [
        "EnergyConsumed",
        "MachineID",
        "EnvTemp",
        "Status",
        "MachineTemp",
        "CO2Level",
        "PowerPeak",
        "Humidity",
        "Pressure"
       ]
      },
      {
       "componentName": "MachineDataSource",
       "entityId": "19d78157-c50e-4b36-92f9-6d3badf21284",
       "properties": [
        "CO2Level",
        "Humidity",
        "PowerPeak",
        "MachineID",
        "MachineTemp",
        "Pressure",
        "EnergyConsumed",
        "EnvTemp",
        "Status"
       ]
      },
      {
       "componentName": "MachineDataSource",
       "entityId": "96437eb2-4774-4e12-8e15-bed7bc943edf",
       "properties": [
        "MachineID",
        "Humidity",
        "MachineTemp",
        "CO2Level",
        "EnergyConsumed",
        "Pressure",
        "EnvTemp",
        "PowerPeak",
        "Status"
       ]
      }
     ]
    },
    {
     "title": "3D Model",
     "type": "grafana-iot-twinmaker-sceneviewer-panel",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {}
     ]
    },
    { "title": "Manufacturing Process", "type": "innius-video-panel", "gridPos": { "h": 14, "w": 12, "x": 0, "y": 11 } },
    {
     "title": "Relationship Graph",
     "type": "text",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 11 },
     "options": {
      "content": "<iframe src=\"http://localhost:5000/graph?machineID=${machineID}\"\r\nwidth=\"100%\" \r\n        height=\"500px\" </iframe>\r\n       "
     }
    }
   ]
  },
  { "title": "Production Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Anomaly_Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "TestDB",
     "rawSql": "\r\nSELECT COUNT(*) AS AnomaliesLastTwoWeeks\r\nFROM MES_Production_Anomalies PA\r\nJOIN MES_ProductionData PD ON PD.RecordID = PA.RecordID\r\nWHERE PA.DetectionTime >= DATEADD(DAY, -21, GETDATE())\r\n  AND PD.MachineID = '${machineID}'\r\n"
    }
   ]
  },
  {
   "title": " Cycle Time Trend",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "sec/cycle" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "TestDB",
     "rawSql": "\r\nSELECT \r\n    StartTime AS time,\r\n    DATEDIFF(MINUTE, StartTime, EndTime) AS value\r\nFROM MES_ProductionData\r\nWHERE $__timeFilter(StartTime)\r\n  AND MachineID = '${machineID}'\r\nORDER BY StartTime ASC\r\n"
    }
   ]
  },
  {
   "title": "anomaly timseries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "TestDB",
     "rawSql": "\r\nSELECT \r\n    CAST(PA.DetectionTime AS DATE) AS time,\r\n    COUNT(*) AS value\r\nFROM MES_Production_Anomalies PA\r\nJOIN MES_ProductionData PD ON PD.RecordID = PA.RecordID\r\nWHERE PA.DetectionTime >= DATEADD(DAY, -21, GETDATE())\r\n  AND PD.MachineID = '${machineID}'\r\nGROUP BY CAST(PA.DetectionTime AS DATE)\r\nORDER BY time ASC\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Production Anomaly",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "TestDB",
     "rawSql": "\r\nSELECT TOP 10 \r\n    PA.RecordID, \r\n    PA.AnomalyScore, \r\n    PA.DetectionTime\r\nFROM MES_Production_Anomalies PA\r\nJOIN MES_ProductionData PD ON PD.RecordID = PA.RecordID\r\nWHERE PD.MachineID = '${machineID}'\r\nORDER BY PA.AnomalyScore ASC\r\n"
    }
   ]
  },
  {
   "title": "Defect Ratio",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "TestDB",
     "rawSql": "\r\nSELECT \r\n    AVG(CAST(Defects AS FLOAT) / NULLIF(QuantityProduced, 0)) AS AvgDefectsRatio\r\nFROM MES_ProductionData\r\nWHERE $__timeFilter(StartTime)\r\n  AND MachineID = '${machineID}'\r\n"
    }
   ]
  },
  {
   "title": "Avg production rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "units/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "TestDB",
     "rawSql": "\r\nSELECT \r\n    AVG(CAST(QuantityProduced AS FLOAT) /\r\n        NULLIF(DATEDIFF(MINUTE, StartTime, EndTime), 0)) AS AvgProductionRate\r\nFROM MES_ProductionData\r\nWHERE $__timeFilter(StartTime)\r\n  AND MachineID = '${machineID}'\r\n"
    }
   ]
  }
 ]
}